---
title: "Homework 5"
author: "Olivia Cecil"
date: "`r Sys.Date()`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warnings = FALSE,
                      messages = FALSE)
```

```{r libraries}
library(readr)
library(dplyr)
library(ggplot2)
library(scales)
library(viridisLite)
library(tigris)
```

## Reading in data, basic cleaning

```{r homicide data }

# read in csv file and add city, state column
homicide_raw <- read_csv("../data/homicide-data.csv") %>% 
  mutate(city_name = paste(city, state, sep = ", "))

# filter to Detroit
detroit_raw <- homicide_raw %>% 
  filter(city_name == "Detroit, MI")


```


```{r mapping data}

# mapping data - select counties containing Detroit metro
det_counties <- county_subdivisions(state = "MI", 
                                   county = "Wayne", 
                                   cb = FALSE, class = "sf")

# add full fips column and update to county names rather than fips codes
det_counties <- det_counties %>% 
  mutate(fips = paste0(STATEFP, COUNTYFP)) %>% 
  mutate(COUNTYFP = case_when(
    COUNTYFP == "163" ~ "Wayne County"
  ))

det_metro <- places(state = "MI") %>% 
  filter(NAME == "Detroit")

det_tract <- tracts(state = "MI", county = "Wayne")

det_blocks <- blocks(state = "MI", county = "Wayne", class = "sf")

# plot layers on example map to determine display
ggplot() +
  geom_sf(data = det_tract, color = "grey") +
  geom_sf(data = det_metro, color = "black", alpha = 0.1) + # alpha transparency
  xlim(c(-83.3, -82.9)) +
  ylim(c(42.25, 42.45))

```



